### ISSUE TITLE
Make it possible to open pages directly from the browser url

### ISSUE THREAD

**Issue by JulsD** [JulsD/React-study#9]

**Comment by phts** [comment]
Actually the problem **only** with names with dot symbol. 

This works [localhost:8080/movie/Pulp Fiction](http://localhost:8080/movie/Pulp%20Fiction) but this [localhost:8080/movie/Kill Bill: Vol. 1](http://localhost:8080/movie/Kill%20Bill:%20Vol.%201) does not.

Check this:
* https://github.com/webpack/webpack-dev-server/issues/454
* https://github.com/webpack/webpack-dev-server/pull/303
